# -*- coding: utf-8 -*-
"""MachineLlab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQw9L6a19fV5mbJIqbvlKbJLFo5OFWak
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')



data_set = '/content/drive/MyDrive/Student/StudentsPerformance.csv'
df=pd.read_csv(data_set)

df.columns

df

print(df.columns)

df.shape

print(df.shape)

df.info()

df.isnull()

df.isnull().sum()

from google.colab import drive
drive.mount('/content/drive')

d_s='/content/drive/MyDrive/Mllab/Wednesday-workingHours.pcap_ISCX.csv'
import pandas as pd
df=pd.read_csv(d_s)
df